# Generated by Django 6.0.2 on 2026-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_broker_user_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for portal access', max_length=254, null=True),
        ),
    ]
